// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drvwerbqqcqvzeagfxci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRydndlcmJxcWNxdnplYWdmeGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTIzODMsImV4cCI6MjA3MjkyODM4M30.UB5pgNuPxRPlvTyknrH5brkDPZAoDws4N8HgjY33I4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
